@startuml "Distruted tx"

actor User
participant "Service A" as A
participant "Service B" as B
queue "Pravega" as Pravega


A -> Pravega  : Open Tx
activate Pravega
A -> Pravega  : Write Events
activate Pravega
deactivate Pravega
A -> B  : Call with txUUID
B -> Pravega : get Tx
B -> Pravega : Write Events
activate Pravega
deactivate Pravega

@enduml