lazy val scala211 = "2.11.12"
lazy val scala212 = "2.12.13"
lazy val scala213 = "2.13.8"
lazy val mainScala = scala213
lazy val allScala = Seq(scala211, scala212, mainScala)

lazy val zioVersion = "2.0.0-RC1"
lazy val pravegaVersion = "0.10.1"

// Allows to silence scalac compilation warnings selectively by code block or file path
// This is only compile time dependency, therefore it does not affect the generated bytecode
// https://github.com/ghik/silencer

inThisBuild(
  List(
    organization := "dev.zio",
    homepage := Some(url("https://github.com/cheleb/zio-pravega")),
    licenses := List(
      "Apache-2.0" -> url("http://www.apache.org/licenses/LICENSE-2.0")
    ),
    useCoursier := false,
    scalaVersion := mainScala,
    crossScalaVersions := allScala,
    Test / parallelExecution := false,
    Test / fork := true,
    run / fork := true,
    pgpPublicRing := file("/tmp/public.asc"),
    pgpSecretRing := file("/tmp/secret.asc"),
    pgpPassphrase := sys.env.get("PGP_PASSWORD").map(_.toArray),
    scmInfo := Some(
      ScmInfo(
        url("https://github.com/cheleb/zio-pravega/"),
        "scm:git:git@github.com:cheleb/zio-pravega.git"
      )
    ),
    developers := List(
      Developer(
        "cheleb",
        "Olivier NOUGUIER",
        "olivier.nouguier@gmail.com",
        url("https://github.com/cheleb")
      )
    ),
    semanticdbEnabled := true, // enable SemanticDB
    semanticdbVersion := scalafixSemanticdb.revision, // only required for Scala 2.x
    scalacOptions ++= Seq(
      "-Wunused:imports",
      "-Wunused",
      "-Wconf:cat=unused:info"
    )
  )
)

val zioConfig =
  Seq("zio-config", "zio-config-magnolia", "zio-config-typesafe").map(d =>
    "dev.zio" %% d % "2.0.0"
  )

lazy val pravega =
  project
    .in(file("."))
    .enablePlugins(BuildInfoPlugin)
    .settings(
      name := "zio-pravega",
      scalafmtOnCompile := true,
      fork := true,
      // workaround for bad constant pool issue
      (Compile / doc) := Def.taskDyn {
        val default = (Compile / doc).taskValue
        if (scalaBinaryVersion.value == "2.11") {
          (Compile / doc / target).toTask
        } else {
          Def.task(default.value)
        }
      }.value,
      Compile / doc / scalacOptions ++= {
        if (scalaBinaryVersion.value == "2.13")
          Seq("-P:silencer:globalFilters=[import scala.collection.compat._]")
        else Seq.empty
      }
    )
    .settings(
      buildInfoKeys := Seq[BuildInfoKey](
        organization,
        name,
        version,
        scalaVersion,
        sbtVersion,
        isSnapshot
      ),
      buildInfoPackage := "zio.pravega"
    )
    .settings(
      resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
      libraryDependencies ++= Seq(
        "dev.zio" %% "zio-streams" % zioVersion,
        "dev.zio" %% "zio-test" % zioVersion % Test,
        "dev.zio" %% "zio-test-sbt" % zioVersion % Test,
        "io.pravega" % "pravega-client" % pravegaVersion,
        "org.testcontainers" % "testcontainers" % "1.16.2" % Test,
        "dev.zio" %% "zio-zmx" % "0.0.11" % Test,
//        "com.fasterxml.jackson.core" % "jackson-databind"         % "2.12.4",
        "ch.qos.logback" % "logback-classic" % "1.2.10" % Test,
        "org.scala-lang.modules" %% "scala-collection-compat" % "2.6.0",
        compilerPlugin(
          "org.typelevel" % "kind-projector" % "0.13.2" cross CrossVersion.full
        )
      ) ++ zioConfig,
      testFrameworks := Seq(new TestFramework("zio.test.sbt.ZTestFramework"))
    )

lazy val docs = project // new documentation project
  .in(file("projects-docs")) // important: it must not be docs/
  .dependsOn(pravega)
  .settings(
    mdocVariables := Map(
      "VERSION" -> version.value
    )
  )
  .enablePlugins(MdocPlugin)

addCommandAlias("fmt", "all scalafmtSbt scalafmt test:scalafmt")
addCommandAlias(
  "check",
  "all scalafmtSbtCheck scalafmtCheck test:scalafmtCheck"
)
