@startuml "distributed-tx"

autonumber

skinparam sequence{
  ParticipantBorderColor DarkBlue
  QueueBorderColor DarkBlue
}


skinparam sequenceMessageAlign center

participant "RestAPI" as Rest

box "Shop" #LightBlue
participant "Service A" as A
queue "Shop Queue" as QueueA
end box
Box "Stock" #LightYellow
participant "Stock Service" as B
queue "Stock Queue" as QueueB
end box
Box "Payment" #PaleGoldenRod
participant "Payment Service" as C
queue "Payment Queue" as QueueC
end box
queue "Event Store" as EventStore

Entity "Aggregate" as Aggregate


Rest -> A : command
activate A #BBBBBB
A -> EventStore  : Open Tx
activate EventStore
A -[#0000FF]-> EventStore  : Write Events
activate EventStore #0000FF
deactivate EventStore
A -> QueueB  : command(txUUID)
deactivate A

B <- QueueB  : trigger
activate B #BBBBBB
B -[#0000FF]-> EventStore : Write Events
activate EventStore #0000FF
deactivate EventStore

B -> QueueC  : command(txUUID)
deactivate B
C <- QueueC  : trigger
activate C #BBBBBB
C -[#0000FF]-> EventStore : Write Events

activate EventStore #0000FF
deactivate EventStore
C -> QueueA  : command(txUUID)
deactivate C
A <- QueueA  : trigger
activate A #BBBBBB
A -> EventStore : Commit Tx

deactivate EventStore
deactivate A

EventStore -> Aggregate : Apply Events


@enduml