@startuml "distributed-tx"

autonumber

skinparam sequence{
  ParticipantBorderColor DarkBlue
  QueueBorderColor DarkBlue
}


skinparam sequenceMessageAlign center

participant "RestAPI" as Rest

box "Shop" #LightBlue
participant "Service" as A
queue "Stream" as QueueA
end box
Box "Stock" #LightYellow
participant "Service" as B
queue "Stream" as QueueB
end box
Box "Payment" #PaleGoldenRod
participant "Service" as C
queue "Stream" as QueueC
end box
queue "Event Store" as EventStore

Entity "Aggregate" as Aggregate


Rest -> QueueA : BookRequest
QueueA -> A
activate A #BBBBBB
A -> EventStore  : Open Tx
activate EventStore
A -[#0000FF]-> EventStore  : BookCommand(id, isbn, quantity)
activate EventStore #0000FF
deactivate EventStore
A -> QueueB  : StockRequest(tx, id, isbn, quantity)
deactivate A

B <- QueueB
activate B #BBBBBB
B -[#0000FF]-> EventStore : BookStockReservation(tx, id, isbn, quantity)
activate EventStore #0000FF
deactivate EventStore

B -> QueueC  : PaymentRequest(tx, id, amount)
deactivate B
C <- QueueC
activate C #BBBBBB
C -[#0000FF]-> EventStore : PaymentConfirmation(tx, id, amount)

activate EventStore #0000FF
deactivate EventStore
C -> QueueA  : PaymentConfirm(txUUID)
deactivate C
A <- QueueA
activate A #BBBBBB
A -> EventStore : Commit Tx

deactivate EventStore
deactivate A

EventStore -> Aggregate : Apply Events


@enduml