name: Scala CI

on:
  push:
    paths-ignore:
      - 'docs/**'    
      - 'website/**'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: sbt
    - name: Run tests crosscompile
      run: sbt ++ test
    - name: Run coverage test
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
