name: Scala CI

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
      - "website/**"
      - ".github/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "website/**"
      - ".github/**"     
  workflow_dispatch:
jobs:
  build:
    environment: Codecov
    runs-on: ubuntu-latest   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "zulu"
          cache: sbt
      - name: Run tests crosscompile
        if: ! contains(github.event.pull_request.labels.*.name, 'publish-reports')
        run: sbt ++ test      
      - name: Run coverage test
        if: contains(github.event.pull_request.labels.*.name, 'publish-reports')
      # Scala 3 is not fully supported for coverage yet
        run: sbt "++ 2.13; coverage; test; coverageReport; coverageAggregate"
      - name: "Upload coverage to Codecov"
        if: contains(github.event.pull_request.labels.*.name, 'publish-reports')
        uses: "codecov/codecov-action@v4"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Fix paths for SonarCloud
        if: contains(github.event.pull_request.labels.*.name, 'publish-reports')
        run: |
            sed -i -e s,`pwd`,/github/workspace,g target/scala-2.13/scoverage-report/scoverage.xml
      - name: SonarCloud scan 
        if: contains(github.event.pull_request.labels.*.name, 'publish-reports')
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "zulu"
          cache: sbt
      - name: Website compile
        run: sbt website
