name: Scala CI

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
      - "website/**"
      - ".github/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "website/**"
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: sbt
      - name: Run tests crosscompile
        run: sbt ++ test
      - name: Run coverage test
        # Scala 3 is not fully supported for coverage yet
        run: sbt "coverage; test; coverageReport"
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v3"
        with:
          token: ${{ secrets.TOKEN }}
          fail_ci_if_error: true
