name: Scala CI

on:
  push:
    paths-ignore:
      - 'docs/**'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests crosscompile
      run: sbt ++ test
    - name: Run coverage test
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
