name: Scala CI

on:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - "master"
    paths-ignore:
      - 'docs/**'    
      - 'website/**'
      - '.github/**' 
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'    
      - 'website/**'    
      - '.github/**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: sbt
    - name: Run tests crosscompile
      run: sbt ++ test
    - name: Run coverage test
      run: sbt coverage test
    - name: Coverage Report
      run: sbt coverageReport
    - name: "Upload coverage to Codecov"
      uses: "codecov/codecov-action@v3"
      with:
        token: ${{ secrets.TOKEN }}
        fail_ci_if_error: true
        
