name: Scala CI

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "master"
    paths-ignore:
      - "docs/**"
      - "website/**"
      - ".github/**"
  pull_request:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "website/**"
      - ".github/**"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Codecov
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "zulu"
          cache: sbt
      - name: Run tests crosscompile
        run: sbt ++ test
      - name: Run coverage test
        # Scala 3 is not fully supported for coverage yet
        run: sbt "++ 2.13.13; coverage; test; coverageReport; coverageAggregate"
      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v4"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
      - name: Fix paths for SonarCloud
        run: |
          sed -i -e s,`pwd`,/github/workspace,g target/scala-2.13/scoverage-report/scoverage.xml
#      - name: SonarCloud scan 
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
