name: Labels code quality checks

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - '**/*.scala'
      - '**/*.sbt'
      - 'modules/**'
jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - name: add label
              uses: actions-ecosystem/action-add-labels@v1
              with:
                labels: needs-code-quality-checks
    call-workflow-2-in-local-repo:
      needs: label
      uses: ./.github/workflows/merge-guard.yaml            