name: Merge Guard

on:
  workflow_dispatch:
  workflow_call: 
jobs:
    merge-guard:
        runs-on: ubuntu-latest
        if: ${{ github.event.label.name == 'needs-code-quality-checks' }}
        steps:
          - name: Check labels
            uses: actions/github-script@v7
            with:
             script: |
                core.setFailed('</3 Code quality checks must be passed.')
                core.info('${{ github.event.pull_request.labels.*.name }}')