name: Merge Guard

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]

jobs:
  merge-guard:
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)
      - name: Check for label
        if: ${{ contains(github.event.*.labels.*.name, 'needs-code-quality-checks') }}
        uses: actions/github-script@v7
        with:
         script: |
          core.setFailed('Pull request is labeled as "needs-code-quality-checks"')
      - name: Ok
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Pull request is not labeled as "needs-code-quality-checks"')