name: Release

on:
  push:
    tags:
     - v*
# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    if: github.event.base_ref=='refs/heads/master'  # check the branch, if it's not master, skip the job.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: sbt
    - name: Run tests crosscompile
      run: sbt ++ test
  publish:
    if: github.event.base_ref=='refs/heads/master' && github.event_name != 'pull_request'  # check the branch, if it's not master, skip the job.
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [build]
    steps:
      - uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: sbt
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  website:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
#          cache: yarn
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: sbt
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - run: sbt website
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: "target/site"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3