name: Release

on:
  push:
    tags:
     - v*

jobs:
  build:
    if: github.event.base_ref=='refs/heads/master'  # check the branch, if it's not master, skip the job.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'zulu'
        cache: sbt
    - name: Run tests crosscompile
      run: sbt ++ test
  publish:
    if: github.event.base_ref=='refs/heads/master' && github.event_name != 'pull_request'  # check the branch, if it's not master, skip the job.
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: [build]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'
          cache: sbt
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
#          cache: yarn
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'zulu'
          cache: sbt
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - run: sbt clean docs/docusaurusCreateSite
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          cd website
          git config --global user.email "olivier.nouguier@gmail.com"
          git config --global user.name "gh-actions"
          yarn install --frozen-lockfile
          yarn deploy