name: Release
on:
  push:
    branches:
      - master
    tags:
     - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
#          cache: yarn
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: sbt clean docs/docusaurusCreateSite
#     - name: Release GitHub package
#       uses: actions/setup-java@v2
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#      - run: sbt publish
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          cd website
          git config --global user.email "olivier.nouguier@gmail.com"
          git config --global user.name "gh-actions"
          yarn install --frozen-lockfile
          yarn deploy
